### ISSUE TITLE
doWebFormats not provided and I wonder where to find it...

### ISSUE THREAD

**Issue by conspect** [miguelsousa/source-sans-pro-subset#1]
Hi Miguel,
nice small scripts, but I wonder where I can find the tool referenced in the makeWebFormats.sh

What is this?

**Comment by miguelsousa** [comment]
It's a shell script that calls these web font conversion tools https://github.com/bramstein/homebrew-webfonttools
I might make it available at https://github.com/adobe-type-tools/shell-scripts someday.
