### ISSUE TITLE
Cooperation adding .loclBGR

### ISSUE THREAD

**Issue by StefanPeev** [miguelsousa/source-sans-pro-subset#2]
I would like to collaborate by adding .loclBGR to locate the modern form of Bulgarian Cyrillic alphabet in Source Sans Pro.

**Comment by miguelsousa** [comment]
@StefanPeev the best way is to add that support in the original [Source Sans Pro](https://github.com/adobe-fonts/source-sans-pro). This repository is a very small subset of that project. I suggest [opening a new issue](https://github.com/adobe-fonts/source-sans-pro/issues) there. If you can provide the Bulgarian glyphs that will help a lot.
